---
title: "Preparing data for analysis"
author: "Antonio Flores"
date: "2024-13-06"
output: html_document
---


# Setup

The following packages are needed for this data processing

```{r}
library(readxl) #for loading Excel files
library(dplyr) #for data processing/cleaning
library(tidyr) #for data processing/cleaning
library(skimr) #for nice visualization of data 
library(here) #to set paths
```


# Data loading

```{r}
data_location <- here::here("data","raw-data","bank-full.csv")
rawdata <- read.csv(data_location, header = TRUE, sep=";")
```


# Check data

Examning metadata by accessing the codebook

```{r}
codebook_location <- 
here::here("data","raw-data","codebook.xlsx")

codebook <- readxl::read_excel(codebook_location, sheet ="Codebook")
print(codebook)
```


Various ways of looking at the data

```{r}
dplyr::glimpse(rawdata)
summary(rawdata)
head(rawdata)
skimr::skim(rawdata)
```


# Cleaning the data

We are mainly converting character variables into factors so we can do some categorical analysis
```{r}
d1 = rawdata |> 
  mutate(job = as.factor(job)) |>
  mutate(marital = as.factor(marital)) |>
  mutate(education = as.factor(education)) |>
  mutate(default = as.factor(default)) |>
  mutate(housing = as.factor(housing)) |>
  mutate(loan = as.factor(loan)) |>
  mutate(education = as.factor(education)) |>
  mutate(contact = as.factor(contact)) |>
  mutate(month = as.factor(month)) |>
  mutate(poutcome = as.factor(poutcome)) |>
  mutate(y = as.factor(y))


summary(d1)
```


All done, data is clean now. 

Assigning data to output variable.

```{r}
processeddata1 <- d1
```


# Save data 

```{r}
save_data_location <- here::here("data","processed-data","processeddata1.rds")
saveRDS(processeddata1, file = save_data_location)
```
